name: Build, & Analyze
on:
    pull_request:
        branches:
            - main

env:
    MODULE_NAME: DemoModule

jobs:
    # Build the module
    build:
        name: Build Module
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.10.2
              with:
                  versionSpec: "5.x"

            - name: Execute GitVersion
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2
              with:
                  useConfigFile: true

            - name: Install required modules
              uses: alt3/install-required-modules-action@main
              with:
                  dataFile: ${{github.workspace}}/Dev/RequiredModules.psd1

            - name: Build module
              id: build
              uses: PoshCode/actions/build-module@v1
              with:
                  path: ${{github.workspace}}/Source
                  version: ${{ steps.gitversion.outputs.semVer }}
                  destination: ${{github.workspace}}/output

            - name: Upload artifact Modules
              uses: actions/upload-artifact@v4
              with:
                  name: Modules
                  path: ${{github.workspace}}/output

            - name: Upload artifact PesterTests
              uses: actions/upload-artifact@v4
              with:
                  name: Tests
                  path: ${{github.workspace}}/Tests

            - name: Upload artifact RequiredModules
              uses: actions/upload-artifact@v4
              with:
                  name: RequiredModules
                  path: ${{github.workspace}}/Dev/RequiredModules.psd1

            - name: Upload artifact PSScriptAnalyzer
              uses: actions/upload-artifact@v4
              with:
                  name: PSScriptAnalyzer
                  path: ${{github.workspace}}/PSScriptAnalyzerSettings.psd1

    # Analyze the module
    analyze:
        name: PSScriptAnalyzer
        runs-on: windows-latest
        needs: build
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Display folder structure
              run: ls -R

            - name: Run PSScriptAnalyzer
              uses: microsoft/psscriptanalyzer-action@v1.1
              with:
                  path: .\
                  recurse: true
                  settings: PSScriptAnalyzerSettings.psd1
                  ignorePattern: "tests"
                  output: results.sarif

            # Upload the SARIF file generated in the previous step
            - name: Upload SARIF results file
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: results.sarif
    test:
        name: Pester Tests
        runs-on: windows-latest
        needs: build
        steps:
            - name: Download artifact Modules
              uses: actions/download-artifact@v4

            - name: Confrim Modules folder exists
              run: ls -R

            - name: Install required modules
              uses: alt3/install-required-modules-action@main
              with:
                  dataFile: ${{github.workspace}}/RequiredModules/RequiredModules.psd1
            - uses: PoshCode/Actions/pester@v1
              with:
                  pesterVersion: 5.5.0
                  codeCoveragePath: Modules/${{env.MODULE_NAME}}
                  moduleUnderTest: ${{env.MODULE_NAME}}
                  additionalModulePaths: ${{github.workspace}}/Modules

            - name: Upload artifact PesterResults
              uses: actions/upload-artifact@v4
              with:
                  name: PesterResults
                  path: ${{github.workspace}}/*.xml
