name: Build, Analyze, and Publish
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    MODULE_NAME: DemoModule

jobs:
    # Build the module
    build:
        name: Build Module
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.10.2
              with:
                  versionSpec: "5.x"

            - name: Execute GitVersion
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2
              with:
                  useConfigFile: true

            - name: Install required modules
              uses: alt3/install-required-modules-action@main
              with:
                  dataFile: ${{github.workspace}}/Dev/RequiredModules.psd1

            - name: Build module
              id: build
              uses: PoshCode/actions/build-module@v1
              with:
                  path: ${{github.workspace}}/Source
                  version: ${{ steps.gitversion.outputs.LegacySemVerPadded }}
                  destination: ${{github.workspace}}/output

            - name: Upload artifact Modules
              uses: actions/upload-artifact@v3
              with:
                  name: Modules
                  path: ${{github.workspace}}/output

            - name: Upload artifact PesterTests
              uses: actions/upload-artifact@v3
              with:
                  name: PesterTests
                  path: ${{github.workspace}}/Tests

            - name: Upload artifact RequiredModules
              uses: actions/upload-artifact@v3
              with:
                  name: RequiredModules
                  path: ${{github.workspace}}/Dev/RequiredModules.psd1

            - name: Upload artifact PSScriptAnalyzer
              uses: actions/upload-artifact@v3
              with:
                  name: PSScriptAnalyzer
                  path: ${{github.workspace}}/PSScriptAnalyzerSettings.psd1

    # Analyze the module
    analyze:
        name: PSScriptAnalyzer
        runs-on: windows-latest
        needs: build
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Display folder structure
              run: ls -R

            - name: Run PSScriptAnalyzer
              uses: microsoft/psscriptanalyzer-action@v1.0
              with:
                  path: .\
                  recurse: true
                  settings: PSScriptAnalyzerSettings.psd1
                  ignorePattern: "tests"
                  output: results.sarif

            # Upload the SARIF file generated in the previous step
            - name: Upload SARIF results file
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: results.sarif
    # -----------------------------------------------------------------------------
    # Publishing stage:
    # - is skipped completely UNLESS on the main branch
    # - is skipped completely UNLESS the commit message contains "[release]"
    # - the psgallery published manifest already contains the bumped module version
    # - the bump-main step bumps copies the artifact manifest to main to match
    #   the PSGallery-published version (without adding [release] to the commit
    #   message)
    # -----------------------------------------------------------------------------
    publish:
        name: Publish
        runs-on: windows-latest
        needs: [analyze]
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')}}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.10.2
              with:
                  versionSpec: "5.x"

            - name: Execute GitVersion
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2
              with:
                  useConfigFile: true

            - name: Download Artifacts
              uses: actions/download-artifact@v3

            - name: Bump Manifest Version on Main
              id: bumpMain
              uses: ./.github/actions/bump-main
              with:
                  artifactPath: Modules/${{env.MODULE_NAME}}

            - name: Publish PowerShell Module
              uses: natescherer/publish-powershell-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  target: packages
                  path: Modules/${{env.MODULE_NAME}}

            - name: Create Github Release
              uses: softprops/action-gh-release@v1
              with:
                  name: Release ${{ steps.gitversion.outputs.LegacySemVerPadded }}
                  tag_name: ${{ env.GitVersion_LegacySemVerPadded }}
                  target_commitish: main
                  draft: false
                  prerelease: false
                  generate_release_notes: true
