name: Build & Publish

on:
    push:
        branches:
            - main

env:
    MODULE_NAME: DemoModule

jobs:
    # Build the module
    build:
        name: Build Module
        runs-on: windows-latest
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.11.0
              with:
                  versionSpec: "5.x"

            - name: Execute GitVersion
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.11.0
              with:
                  useConfigFile: true

            - name: Install required modules
              uses: alt3/install-required-modules-action@main
              with:
                  dataFile: ${{github.workspace}}/Dev/RequiredModules.psd1

            - name: Build module
              id: build
              uses: PoshCode/actions/build-module@v1
              with:
                  path: ${{github.workspace}}/Source
                  version: ${{ steps.gitversion.outputs.LegacySemVerPadded }}
                  destination: ${{github.workspace}}/output

            - name: Upload artifact Modules
              uses: actions/upload-artifact@v4
              with:
                  name: Modules
                  path: ${{github.workspace}}/output

            - name: Upload artifact PesterTests
              uses: actions/upload-artifact@v4
              with:
                  name: PesterTests
                  path: ${{github.workspace}}/Tests

            - name: Upload artifact RequiredModules
              uses: actions/upload-artifact@v4
              with:
                  name: RequiredModules
                  path: ${{github.workspace}}/Dev/RequiredModules.psd1

            - name: Upload artifact PSScriptAnalyzer
              uses: actions/upload-artifact@v4
              with:
                  name: PSScriptAnalyzer
                  path: ${{github.workspace}}/PSScriptAnalyzerSettings.psd1

    publish:
        runs-on: windows-latest
        needs: build
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')}}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.11.0
              with:
                  versionSpec: "5.x"

            - name: Execute GitVersion
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.11.0
              with:
                  useConfigFile: true

            - name: Download Artifacts
              uses: actions/download-artifact@v4

            - name: Bump Manifest Version on Main
              id: bumpMain
              uses: ./.github/actions/bump-main
              with:
                  artifactPath: Modules/${{env.MODULE_NAME}}

            - name: Publish PowerShell Module
              uses: natescherer/publish-powershell-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  target: packages
                  path: Modules/${{env.MODULE_NAME}}/${{steps.gitversion.outputs.LegacySemVerPadded}}

            - name: Create Github Release
              uses: softprops/action-gh-release@v1
              with:
                  name: Release ${{ steps.gitversion.outputs.LegacySemVerPadded }}
                  tag_name: ${{ env.GitVersion_LegacySemVerPadded }}
                  target_commitish: main
                  draft: false
                  prerelease: false
                  generate_release_notes: true
