name: Publish

on:
    push:
        branches:
            - main

env:
    MODULE_NAME: DSG.Ec.Core

jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')}}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.10.2
              with:
                  versionSpec: "5.x"

            - name: Execute GitVersion
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2
              with:
                  useConfigFile: true

            - name: Download Artifacts
              uses: actions/download-artifact@v3

            - name: Bump Manifest Version on Main
              id: bumpMain
              uses: ./.github/actions/bump-main
              with:
                  artifactPath: Modules/${{env.MODULE_NAME}}

            - name: Publish PowerShell Module
              uses: natescherer/publish-powershell-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  target: packages
                  path: Modules/${{env.MODULE_NAME}}/${{steps.gitversion.outputs.LegacySemVerPadded}}

            - name: Create Github Release
              uses: softprops/action-gh-release@v1
              with:
                  name: Release ${{ steps.gitversion.outputs.LegacySemVerPadded }}
                  tag_name: ${{ env.GitVersion_LegacySemVerPadded }}
                  target_commitish: main
                  draft: false
                  prerelease: false
                  generate_release_notes: true
